// CORS policy.
//
// What this defends against: a page on the open web (https://evil.com, an ad frame, a
// malicious doc) making cross-origin requests to the API listening on the user's own
// machine. The previous `Access-Control-Allow-Origin: *` allowed exactly that — and since
// the auth guard also accepts the token as a `?token=` query parameter, any page that ever
// learned the token had a clean path into the vault.
//
// What this does NOT defend against, and is not meant to: non-browser clients. The MCP
// server (src/mcp/client.js), the test suite and any script use Node `fetch`, which sends
// no `Origin` header at all. CORS is a browser mechanism enforced by the browser; it has
// nothing to say about them. Their gate is the API token, checked in api.js.
//
// Three cases, in order:
//   1. No Origin        → pass through, set no ACAO. Not a browser request.
//   2. Origin allowed   → echo it, with `Vary: Origin` since the value is now conditional.
//   3. Origin rejected  → set no ACAO and refuse. The browser would block the response
//                         either way; refusing outright also stops a "simple" cross-origin
//                         POST (which is not preflighted) from executing unread.

import { getAllowedOrigins } from '../access/primitives/config.js';

const ALLOWED_HEADERS = [
    'Origin',
    'X-Requested-With',
    'Content-Type',
    'Accept',
    'Authorization',
    // The MCP server tags its requests with this so routes/diary.js can apply the
    // AI-assistant privacy gate. Never actually preflighted today (Node sends no Origin),
    // but omitting it would silently break any future browser client that identifies
    // itself the same way.
    'X-Flashback-Client',
].join(', ');

const ALLOWED_METHODS = 'GET, POST, PUT, PATCH, DELETE, OPTIONS';

// Loopback, any port. The alternative — enumerating the Vite dev port and the API's own
// port — breaks the `dev:api` / `dev:web` flows, which run the renderer on :51234 and set
// no NODE_ENV to detect themselves by, and it would break again the next time a port
// moves. Treating loopback as one trust boundary is also the honest model: another origin
// on 127.0.0.1 means code is already running on this machine, and it still needs the API
// token to get anywhere.
const LOOPBACK = /^https?:\/\/(localhost|127\.0\.0\.1|\[::1\])(:\d+)?$/;

function isAllowed(origin) {
    // The packaged renderer is loaded with loadFile() from dist-react/, so its pages are
    // file:// — an opaque origin, serialized as the literal string "null".
    if (origin === 'null') return true;
    if (LOOPBACK.test(origin)) return true;
    // Extra origins named in config.json. Empty on a desktop install; this is the field a
    // Flashback Server deployment sets to name its own web client.
    return getAllowedOrigins().includes(origin);
}

export default (req, res, next) => {
    const origin = req.headers.origin;

    if (!origin) return next();

    if (!isAllowed(origin)) {
        // Explicit 403 rather than a bare missing header: a rejected preflight otherwise
        // surfaces in the console as an unexplained CORS failure with nothing to grep for.
        return res.status(403).json({ error: `Origin not allowed: ${origin}` });
    }

    res.header('Access-Control-Allow-Origin', origin);
    res.header('Vary', 'Origin');
    res.header('Access-Control-Allow-Headers', ALLOWED_HEADERS);

    // Preflights are answered here and NOT passed down the stack. They must stay ahead of
    // the auth guard in api.js: a preflight is generated by the browser and cannot carry
    // an Authorization header, so letting it reach the guard would 401 every browser
    // client before its real request was ever sent.
    if (req.method === 'OPTIONS') {
        res.header('Access-Control-Allow-Methods', ALLOWED_METHODS);
        res.header('Access-Control-Max-Age', '86400');
        return res.status(204).end();
    }

    return next();
};

// Exported so the policy can be unit-tested without standing up an Express app.
export { isAllowed };
